### ISSUE TITLE
Domain's down.

### ISSUE THREAD

**Issue by Izhaki** [onlurking/interneting-is-hard#5]
Sure you are aware, but https://internetingishard.com/ is down.

**Comment by onlurking** [comment]
Hi @Izhaki, I'm not the creator of the site, this is just a mirror, from time to time the internetingishard site goes down, so I've made a copy where I host on https://internetingishard.netlify.app/html-and-css/ (which includes some fixes and the feature of zooming the image examples).

**Comment by Izhaki** [comment]
Thanks!
